<main class="p-5 sm:p-8 lg:p-10">
    <div class="mx-auto max-w-6xl space-y-7">
        <div><span class="mb-4 grid size-12 place-items-center rounded-2xl bg-[#fde9e3] text-[#b85240] dark:bg-[#e58775]/15 dark:text-[#f1ad9e]"><flux:icon.cog-6-tooth class="size-6" /></span><flux:heading size="xl">Configurações</flux:heading><flux:text class="mt-2">Gerencie sua conta, segurança e experiência no painel.</flux:text></div>

        <div class="grid gap-6 lg:grid-cols-[15rem_minmax(0,1fr)]">
            <nav class="h-fit space-y-1 rounded-2xl border border-stone-200 bg-white p-2 dark:border-white/10 dark:bg-zinc-900 lg:sticky lg:top-6">
                @foreach([['profile','user-circle','Perfil'],['security','lock-closed','Segurança'],['appearance','paint-brush','Aparência'],['account','credit-card','Conta e plano']] as [$key,$icon,$label])
                    <button type="button" wire:click="$set('section','{{ $key }}')" @class(['flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition', 'bg-[#fde9e3] font-medium text-[#7d382f] dark:bg-[#e58775]/15 dark:text-[#f1ad9e]' => $section === $key, 'text-stone-600 hover:bg-stone-100 dark:text-stone-400 dark:hover:bg-white/5' => $section !== $key])><flux:icon :name="$icon" class="size-4.5" />{{ $label }}</button>
                @endforeach
            </nav>

            <div class="min-w-0">
                @if($section === 'profile')
                    <section class="overflow-hidden rounded-3xl border border-stone-200 bg-white dark:border-white/10 dark:bg-zinc-900"><header class="border-b border-stone-200 p-6 dark:border-white/10"><flux:heading size="lg">Informações pessoais</flux:heading><flux:text class="mt-1">Dados usados para identificar sua conta.</flux:text></header><form wire:submit="updateProfile" class="space-y-6 p-6"><div class="flex items-center gap-4 rounded-2xl bg-stone-50 p-4 dark:bg-white/[.03]"><flux:avatar size="lg" :name="auth()->user()->name" /><div><p class="font-medium">{{ auth()->user()->name }}</p><p class="text-xs text-stone-500">{{ auth()->user()->email }}</p></div></div><flux:input wire:model="profile.name" label="Nome completo" icon="user" autocomplete="name" required /><flux:input wire:model="profile.email" type="email" label="E-mail" icon="envelope" autocomplete="email" required />@if(auth()->user()->hasVerifiedEmail())<p class="flex items-center gap-2 text-xs text-emerald-600 dark:text-emerald-400"><flux:icon.check-circle class="size-4" /> E-mail confirmado</p>@else<p class="flex items-center gap-2 text-xs text-amber-600 dark:text-amber-400"><flux:icon.exclamation-triangle class="size-4" /> Confirmação de e-mail pendente</p>@endif<div class="flex justify-end border-t border-stone-100 pt-5 dark:border-white/10"><flux:button type="submit" variant="primary" icon="check">Salvar alterações</flux:button></div></form></section>
                @elseif($section === 'security')
                    <section class="overflow-hidden rounded-3xl border border-stone-200 bg-white dark:border-white/10 dark:bg-zinc-900"><header class="border-b border-stone-200 p-6 dark:border-white/10"><flux:heading size="lg">Alterar senha</flux:heading><flux:text class="mt-1">Use uma senha forte e exclusiva para proteger sua conta.</flux:text></header><form wire:submit="updatePassword" class="space-y-6 p-6"><div class="rounded-2xl border border-[#e58775]/20 bg-[#fff7f4] p-4 text-sm text-stone-600 dark:bg-[#e58775]/5 dark:text-stone-400"><span class="mb-1 flex items-center gap-2 font-medium text-stone-800 dark:text-stone-200"><flux:icon.shield-check class="size-4 text-[#b85240]" /> Recomendação de segurança</span>Combine letras maiúsculas e minúsculas, números e símbolos.</div><flux:input wire:model="password.current_password" type="password" label="Senha atual" icon="key" viewable autocomplete="current-password" required /><div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="password.password" type="password" label="Nova senha" icon="lock-closed" viewable autocomplete="new-password" required /><flux:input wire:model="password.password_confirmation" type="password" label="Confirmar nova senha" icon="lock-closed" viewable autocomplete="new-password" required /></div><div class="flex justify-end border-t border-stone-100 pt-5 dark:border-white/10"><flux:button type="submit" variant="primary" icon="shield-check">Atualizar senha</flux:button></div></form></section>
                @elseif($section === 'appearance')
                    <section class="overflow-hidden rounded-3xl border border-stone-200 bg-white dark:border-white/10 dark:bg-zinc-900"><header class="border-b border-stone-200 p-6 dark:border-white/10"><flux:heading size="lg">Aparência do painel</flux:heading><flux:text class="mt-1">Escolha como a interface deve ser exibida.</flux:text></header><div class="p-6"><div class="grid gap-4 sm:grid-cols-3">@foreach([['light','sun','Claro','Interface sempre clara.'],['dark','moon','Escuro','Mais confortável à noite.'],['system','computer-desktop','Sistema','Segue seu dispositivo.']] as [$value,$icon,$label,$description])<button type="button" x-on:click="$flux.appearance = '{{ $value }}'" class="group rounded-2xl border border-stone-200 p-4 text-left transition hover:border-[#e58775] dark:border-white/10" x-bind:class="$flux.appearance === '{{ $value }}' ? 'ring-2 ring-[#e58775] border-[#e58775] bg-[#fff7f4] dark:bg-[#e58775]/10' : ''"><span class="grid size-10 place-items-center rounded-xl bg-stone-100 text-stone-600 group-hover:text-[#b85240] dark:bg-white/5 dark:text-stone-300"><flux:icon :name="$icon" class="size-5" /></span><p class="mt-4 font-medium">{{ $label }}</p><p class="mt-1 text-xs leading-5 text-stone-500">{{ $description }}</p><span x-show="$flux.appearance === '{{ $value }}'" class="mt-3 flex items-center gap-1.5 text-xs font-medium text-[#a94737] dark:text-[#f1ad9e]"><flux:icon.check-circle class="size-4" /> Selecionado</span></button>@endforeach</div><div class="mt-6 rounded-2xl bg-stone-50 p-4 text-xs leading-5 text-stone-500 dark:bg-white/[.03]">A preferência é salva neste navegador e também será usada no builder. As cores do convite não são alteradas pelo tema do painel.</div></div></section>
                @else
                    <section class="overflow-hidden rounded-3xl border border-stone-200 bg-white dark:border-white/10 dark:bg-zinc-900"><header class="border-b border-stone-200 p-6 dark:border-white/10"><flux:heading size="lg">Conta e plano</flux:heading><flux:text class="mt-1">Resumo da assinatura e dos recursos disponíveis.</flux:text></header><div class="space-y-5 p-6"><div class="relative overflow-hidden rounded-3xl bg-[#f6e5df] p-6 dark:bg-[#1c1917]"><span class="absolute -right-10 -top-14 size-40 rounded-full border-[22px] border-[#e58775]/60"></span><div class="relative"><span class="text-[10px] font-bold uppercase tracking-[.16em] text-[#a94737] dark:text-[#f1ad9e]">Plano atual</span><h3 class="mt-2 text-2xl font-semibold">{{ auth()->user()->plan === 'premium' ? 'Premium' : 'Gratuito' }}</h3><p class="mt-2 max-w-md text-sm text-stone-600 dark:text-stone-400">{{ auth()->user()->plan === 'premium' ? 'Todos os blocos premium e recursos avançados estão liberados.' : 'Comece a criar eventos e faça upgrade quando precisar de mais recursos.' }}</p></div></div><div class="grid gap-3 sm:grid-cols-2"><div class="rounded-2xl border border-stone-200 p-4 dark:border-white/10"><span class="text-xs text-stone-500">Membro desde</span><p class="mt-1 font-medium">{{ auth()->user()->created_at->format('d/m/Y') }}</p></div><div class="rounded-2xl border border-stone-200 p-4 dark:border-white/10"><span class="text-xs text-stone-500">Status da conta</span><p class="mt-1 flex items-center gap-2 font-medium"><span class="size-2 rounded-full bg-emerald-500"></span> Ativa</p></div></div>@if(auth()->user()->plan !== 'premium')<div class="flex flex-col justify-between gap-4 rounded-2xl border border-[#e58775]/25 p-5 sm:flex-row sm:items-center"><div><p class="font-medium">Desbloqueie recursos Premium</p><p class="mt-1 text-sm text-stone-500">Galeria, mapa, vídeo e contagem regressiva.</p></div><flux:button variant="primary" icon="sparkles">Conhecer Premium</flux:button></div>@endif</div></section>
                @endif
            </div>
        </div>
    </div>
</main>
