<main class="p-5 sm:p-8 lg:p-10">
    @php($maxGrowth = max(1, collect($this->growth)->max('users')))
    <div class="mx-auto max-w-7xl space-y-7">
        <header class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span class="text-xs font-semibold uppercase tracking-[.16em] text-[#b85240] dark:text-[#f1ad9e]">Administração</span><flux:heading size="xl" class="mt-2">Visão geral do SaaS</flux:heading><flux:text class="mt-2">Receita, assinaturas e atividade da plataforma.</flux:text></div><div class="flex gap-2"><flux:button variant="ghost" icon="users" :href="route('admin.users.index')" wire:navigate>Usuários</flux:button><flux:button variant="primary" icon="credit-card" :href="route('admin.subscriptions.index')" wire:navigate>Assinaturas</flux:button></div></header>

        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            @foreach([['Receita mensal estimada','R$ '.number_format($this->metrics['estimated_mrr'],2,',','.'),'banknotes'],['Assinantes Premium',number_format($this->metrics['premium_users'],0,',','.'),'sparkles'],['Taxa de conversão',number_format($this->metrics['conversion_rate'],1,',','.').'%','arrow-trending-up'],['Novos neste mês',number_format($this->metrics['new_users_this_month'],0,',','.'),'user-plus']] as [$label,$value,$icon])<div class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-zinc-900"><div class="flex items-start justify-between"><div><p class="text-xs text-stone-500">{{ $label }}</p><p class="mt-3 text-2xl font-semibold tracking-tight">{{ $value }}</p></div><span class="grid size-10 place-items-center rounded-xl bg-[#fde9e3] text-[#b85240] dark:bg-[#e58775]/15 dark:text-[#f1ad9e]"><flux:icon :name="$icon" class="size-5" /></span></div></div>@endforeach
        </div>

        <div class="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(19rem,.65fr)]">
            <section class="rounded-3xl border border-stone-200 bg-white p-6 dark:border-white/10 dark:bg-zinc-900"><div class="flex items-start justify-between"><div><h2 class="font-semibold">Crescimento de usuários</h2><p class="mt-1 text-xs text-stone-500">Novas contas nos últimos seis meses.</p></div><flux:badge color="zinc">{{ $this->metrics['users'] }} contas</flux:badge></div><div class="mt-8 flex h-52 items-end gap-3 sm:gap-5">@foreach($this->growth as $month)<div class="flex h-full flex-1 flex-col justify-end gap-2"><span class="text-center text-xs font-medium">{{ $month['users'] }}</span><div class="group relative mx-auto w-full max-w-14 overflow-hidden rounded-t-xl bg-stone-100 dark:bg-white/5" style="height: {{ max(8, ($month['users'] / $maxGrowth) * 100) }}%"><div class="absolute inset-0 bg-[#e58775] transition group-hover:bg-[#d86d59]"></div></div><span class="text-center text-[10px] font-semibold uppercase text-stone-400">{{ $month['label'] }}</span></div>@endforeach</div></section>
            <section class="overflow-hidden rounded-3xl border border-stone-200 bg-white dark:border-white/10 dark:bg-zinc-900"><header class="border-b border-stone-200 p-5 dark:border-white/10"><h2 class="font-semibold">Distribuição dos planos</h2><p class="mt-1 text-xs text-stone-500">Base atual de clientes.</p></header><div class="space-y-5 p-5"><div><div class="mb-2 flex justify-between text-sm"><span>Premium</span><span class="font-semibold">{{ $this->metrics['premium_users'] }}</span></div><div class="h-2 overflow-hidden rounded-full bg-stone-100 dark:bg-white/5"><div class="h-full rounded-full bg-[#e58775]" style="width: {{ $this->metrics['users'] ? ($this->metrics['premium_users'] / $this->metrics['users']) * 100 : 0 }}%"></div></div></div><div><div class="mb-2 flex justify-between text-sm"><span>Gratuito</span><span class="font-semibold">{{ $this->metrics['free_users'] }}</span></div><div class="h-2 overflow-hidden rounded-full bg-stone-100 dark:bg-white/5"><div class="h-full rounded-full bg-stone-400 dark:bg-stone-600" style="width: {{ $this->metrics['users'] ? ($this->metrics['free_users'] / $this->metrics['users']) * 100 : 0 }}%"></div></div></div><div class="rounded-2xl bg-[#fff7f4] p-4 dark:bg-[#e58775]/5"><p class="text-xs text-stone-500">Valor do Premium</p><p class="mt-1 text-lg font-semibold">R$ {{ number_format(config('plans.premium.monthly_price'),2,',','.') }}<span class="text-xs font-normal text-stone-400">/mês</span></p></div></div></section>
        </div>

        <div class="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Usuários verificados',$this->metrics['verified_users'],'check-badge'],['Eventos criados',$this->metrics['events'],'calendar-days'],['Sites publicados',$this->metrics['published_sites'],'rocket-launch'],['Arquivos enviados',$this->metrics['media_assets'],'photo']] as [$label,$value,$icon])<div class="flex items-center gap-4 rounded-2xl border border-stone-200 bg-white p-4 dark:border-white/10 dark:bg-zinc-900"><span class="grid size-10 place-items-center rounded-xl bg-stone-100 text-stone-500 dark:bg-white/5 dark:text-stone-400"><flux:icon :name="$icon" class="size-5" /></span><div><p class="text-xl font-semibold">{{ number_format($value,0,',','.') }}</p><p class="text-xs text-stone-500">{{ $label }}</p></div></div>@endforeach</div>

        <section class="overflow-hidden rounded-3xl border border-stone-200 bg-white dark:border-white/10 dark:bg-zinc-900"><header class="flex items-center justify-between border-b border-stone-200 px-5 py-4 dark:border-white/10"><div><h2 class="font-semibold">Assinantes Premium recentes</h2><p class="mt-1 text-xs text-stone-500">Contas Premium atualizadas recentemente.</p></div><flux:button variant="ghost" size="sm" :href="route('admin.subscriptions.index')" wire:navigate>Gerenciar</flux:button></header>@forelse($this->recentSubscribers as $subscriber)<div class="flex flex-col gap-3 border-b border-stone-100 p-4 last:border-0 dark:border-white/5 sm:flex-row sm:items-center"><flux:avatar size="sm" :name="$subscriber->name" /><div class="min-w-0 flex-1"><p class="truncate text-sm font-medium">{{ $subscriber->name }}</p><p class="truncate text-xs text-stone-500">{{ $subscriber->email }}</p></div><div class="text-xs text-stone-500">{{ $subscriber->events_count }} evento(s)</div><flux:badge color="amber" icon="sparkles">Premium</flux:badge><span class="text-xs text-stone-400">{{ $subscriber->updated_at->diffForHumans() }}</span></div>@empty<div class="px-5 py-12 text-center"><flux:icon.credit-card class="mx-auto size-8 text-stone-300" /><p class="mt-3 text-sm text-stone-500">Ainda não há assinantes Premium.</p></div>@endforelse</section>
    </div>
</main>
