<main class="p-5 sm:p-8 lg:p-10">
    <div class="mx-auto max-w-7xl space-y-7">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><flux:heading size="xl">Usuários</flux:heading><flux:text class="mt-2">Contas cadastradas na plataforma.</flux:text></div><flux:input wire:model.live.debounce.300ms="search" icon="magnifying-glass" placeholder="Buscar nome ou e-mail" class="sm:w-80" clearable /></div>
        <div class="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-white/10 dark:bg-zinc-900">
            <div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b border-stone-200 bg-stone-50 text-xs uppercase tracking-wide text-stone-500 dark:border-white/10 dark:bg-white/5"><tr><th class="px-5 py-4">Usuário</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Papéis</th><th class="px-5 py-4">Cadastro</th></tr></thead><tbody class="divide-y divide-stone-100 dark:divide-white/5">@forelse ($this->users as $user)<tr><td class="px-5 py-4"><div class="flex items-center gap-3"><flux:avatar size="sm" :name="$user->name" /><div><div class="font-medium">{{ $user->name }}</div><div class="text-stone-500">{{ $user->email }}</div></div></div></td><td class="px-5 py-4"><flux:badge size="sm" :color="$user->hasVerifiedEmail() ? 'green' : 'zinc'">{{ $user->hasVerifiedEmail() ? 'Verificado' : 'Pendente' }}</flux:badge></td><td class="px-5 py-4 text-stone-500">{{ $user->roles->pluck('name')->join(', ') ?: 'Cliente' }}</td><td class="px-5 py-4 text-stone-500">{{ $user->created_at->format('d/m/Y') }}</td></tr>@empty<tr><td colspan="4" class="px-5 py-14 text-center text-stone-500">Nenhum usuário encontrado.</td></tr>@endforelse</tbody></table></div>
            @if ($this->users->hasPages())<div class="border-t border-stone-200 px-5 py-4 dark:border-white/10">{{ $this->users->links() }}</div>@endif
        </div>
    </div>
</main>
