<main class="p-5 sm:p-8 lg:p-10">
    <div class="mx-auto max-w-7xl space-y-7">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span class="mb-4 grid size-12 place-items-center rounded-2xl bg-[#fde9e3] text-[#b85240] dark:bg-[#e58775]/15 dark:text-[#f1ad9e]"><flux:icon.window class="size-6" /></span><flux:heading size="xl">Sites</flux:heading><flux:text class="mt-2">Gerencie os convites, publicações e endereços públicos.</flux:text></div><flux:button variant="primary" icon="plus" :href="route('client.events.index')" wire:navigate>Novo site</flux:button></div>
        <div class="flex flex-col gap-3 rounded-2xl border border-stone-200 bg-white p-3 dark:border-white/10 dark:bg-zinc-900 sm:flex-row"><flux:input wire:model.live.debounce.300ms="search" icon="magnifying-glass" placeholder="Buscar por nome ou endereço..." class="flex-1" /><flux:select wire:model.live="status" class="sm:w-44"><flux:select.option value="all">Todos os status</flux:select.option><flux:select.option value="draft">Rascunhos</flux:select.option><flux:select.option value="published">Publicados</flux:select.option></flux:select></div>
        @if($this->sites->isEmpty())
            <div class="rounded-3xl border border-dashed border-stone-300 px-6 py-16 text-center dark:border-white/15"><flux:icon.window class="mx-auto size-9 text-stone-400" /><flux:heading size="lg" class="mt-4">Nenhum site encontrado</flux:heading><flux:text class="mt-2">Crie um evento para gerar seu primeiro site.</flux:text></div>
        @else
            <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@foreach($this->sites as $site)<article class="overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg dark:border-white/10 dark:bg-zinc-900"><div class="relative h-36 bg-[#f6e5df] p-5 dark:bg-[#201d1b]"><span class="absolute -right-10 -top-12 size-36 rounded-full border-[20px] border-[#e58775]/70"></span><flux:badge :color="$site->status === 'published' ? 'lime' : 'zinc'">{{ $site->status === 'published' ? 'Publicado' : 'Rascunho' }}</flux:badge><h2 class="relative mt-6 truncate text-xl font-semibold">{{ $site->name }}</h2><p class="relative mt-1 truncate text-xs text-stone-500 dark:text-stone-400">/{{ $site->slug }}</p></div><div class="space-y-4 p-5"><div class="flex items-center justify-between text-xs text-stone-500"><span>{{ $site->pages->count() }} página(s)</span><span>{{ $site->published_at?->format('d/m/Y H:i') ?? 'Nunca publicado' }}</span></div><div class="grid grid-cols-2 gap-2"><flux:button variant="primary" icon="paint-brush" :href="route('client.builder.edit', ['event' => $site->event, 'page' => $site->pages->first()])" wire:navigate>Editar</flux:button>@if($site->status === 'published')<flux:button variant="ghost" icon="eye-slash" wire:click="unpublish({{ $site->id }})">Ocultar</flux:button>@else<flux:button variant="ghost" icon="rocket-launch" wire:click="publish({{ $site->id }})">Publicar</flux:button>@endif</div></div></article>@endforeach</div>
        @endif
    </div>
</main>
