<main class="p-5 sm:p-8 lg:p-10">
    @php
        $hour = now()->hour;
        $greeting = $hour < 12 ? 'Bom dia' : ($hour < 18 ? 'Boa tarde' : 'Boa noite');
        $featured = $this->recentEvents->first();
        $setupDone = collect($this->setup)->where('done', true)->count();
        $setupPercent = (int) (($setupDone / count($this->setup)) * 100);
    @endphp
    <div class="mx-auto max-w-7xl space-y-7">
        <header class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><flux:text class="mb-1 text-[#b85240] dark:text-[#f1ad9e]">{{ $greeting }}, {{ str(auth()->user()->name)->before(' ') }}</flux:text><flux:heading size="xl">Seu espaço de criação</flux:heading><flux:text class="mt-2">Acompanhe seus eventos e continue de onde parou.</flux:text></div><div class="flex gap-2"><flux:button variant="ghost" icon="photo" :href="route('client.media.index')" wire:navigate>Mídia</flux:button><flux:button variant="primary" icon="plus" :href="route('client.events.index')" wire:navigate>Novo evento</flux:button></div></header>

        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            @foreach([['Eventos',$this->metrics['events'],'calendar-days',route('client.events.index')],['Sites publicados',$this->metrics['published'],'rocket-launch',route('client.sites.index')],['Arquivos de mídia',$this->metrics['media'],'photo',route('client.media.index')],['Pessoas na equipe',$this->metrics['team'],'user-group',route('client.team.index')]] as [$label,$value,$icon,$route])
                <a href="{{ $route }}" wire:navigate class="group flex items-center gap-4 rounded-2xl border border-stone-200 bg-white p-4 transition hover:-translate-y-0.5 hover:border-[#e58775]/60 hover:shadow-lg dark:border-white/10 dark:bg-zinc-900"><span class="grid size-11 shrink-0 place-items-center rounded-2xl bg-[#fde9e3] text-[#b85240] dark:bg-[#e58775]/10 dark:text-[#f1ad9e]"><flux:icon :name="$icon" class="size-5" /></span><div class="min-w-0 flex-1"><p class="text-2xl font-semibold tracking-tight">{{ $value }}</p><p class="truncate text-xs text-stone-500">{{ $label }}</p></div><flux:icon.arrow-up-right class="size-4 text-stone-300 transition group-hover:text-[#b85240]" /></a>
            @endforeach
        </div>

        <div class="grid gap-5 xl:grid-cols-[minmax(0,1.6fr)_minmax(18rem,.7fr)]">
            <section class="relative min-h-72 overflow-hidden rounded-[2rem] border border-[#e8cfc7] bg-[#f6e5df] p-7 shadow-sm dark:border-white/10 dark:bg-[#1c1917] sm:p-9">
                <span class="absolute -right-16 -top-20 size-64 rounded-full border-[32px] border-[#e58775]/65"></span><span class="absolute -bottom-20 right-44 size-40 rounded-full border-[20px] border-white/30 dark:border-white/5"></span>
                <div class="relative flex h-full max-w-xl flex-col justify-center">
                    @if($featured)
                        <span class="text-[11px] font-bold uppercase tracking-[.16em] text-[#a94737] dark:text-[#f1ad9e]">Continue seu projeto</span><h2 class="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">{{ $featured->name }}</h2><p class="mt-3 max-w-lg text-sm leading-6 text-stone-600 dark:text-stone-400">Seu convite está {{ $featured->site->status === 'published' ? 'publicado' : 'salvo como rascunho' }}. Abra o editor para revisar o conteúdo e continuar personalizando.</p><div class="mt-6 flex flex-wrap gap-2"><flux:button variant="primary" icon="paint-brush" :href="route('client.builder.edit', ['event' => $featured, 'page' => $featured->site->pages->first()])" wire:navigate>Continuar editando</flux:button><flux:button variant="ghost" icon="window" :href="route('client.sites.index')" wire:navigate>Gerenciar site</flux:button></div>
                    @else
                        <span class="text-[11px] font-bold uppercase tracking-[.16em] text-[#a94737] dark:text-[#f1ad9e]">Primeiro passo</span><h2 class="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Crie algo memorável</h2><p class="mt-3 max-w-lg text-sm leading-6 text-stone-600 dark:text-stone-400">Crie seu primeiro evento e receba automaticamente um site e uma página prontos para personalizar no builder.</p><flux:button class="mt-6 w-fit" variant="primary" icon="sparkles" :href="route('client.events.index')" wire:navigate>Criar primeiro evento</flux:button>
                    @endif
                </div>
            </section>

            @if($this->nextEvent)
                @php($nextCover = $this->nextEvent->site->coverImageUrl())
                <section class="overflow-hidden rounded-[2rem] border border-stone-200 bg-white dark:border-white/10 dark:bg-zinc-900">@if($nextCover)<div class="relative h-32 overflow-hidden"><img src="{{ $nextCover }}" alt="" class="h-full w-full object-cover"><span class="absolute inset-0 bg-[#1c1917]/25"></span><span class="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-[#914032]">Próximo evento</span></div>@else<div class="flex h-24 items-center justify-between bg-[#fff1ec] px-5 dark:bg-[#e58775]/10"><span class="text-[10px] font-bold uppercase tracking-[.16em] text-[#a94737] dark:text-[#f1ad9e]">Próximo evento</span><flux:icon.calendar-days class="size-7 text-[#e58775]" /></div>@endif<div class="p-5"><h3 class="truncate text-lg font-semibold">{{ $this->nextEvent->name }}</h3><div class="mt-4 flex items-center gap-3 rounded-2xl bg-stone-50 p-3 dark:bg-white/[.03]"><div class="grid size-11 place-items-center rounded-xl bg-white text-center shadow-sm dark:bg-zinc-800"><span class="text-[9px] font-bold uppercase text-[#b85240]">{{ $this->nextEvent->event_date->translatedFormat('M') }}</span><span class="-mt-1 text-lg font-semibold">{{ $this->nextEvent->event_date->format('d') }}</span></div><div><p class="text-sm font-medium">{{ $this->nextEvent->event_date->translatedFormat('l') }}</p><p class="text-xs text-stone-500">às {{ $this->nextEvent->event_date->format('H:i') }}</p></div></div><flux:button class="mt-4 w-full" variant="ghost" icon:trailing="arrow-right" :href="route('client.events.index')" wire:navigate>Ver detalhes</flux:button></div></section>
            @else
                <section class="rounded-[2rem] border border-stone-200 bg-white p-6 dark:border-white/10 dark:bg-zinc-900"><div class="flex items-start justify-between"><div><span class="text-[10px] font-bold uppercase tracking-[.16em] text-stone-400">Primeiros passos</span><h3 class="mt-2 text-lg font-semibold">Prepare sua conta</h3></div><span class="grid size-11 place-items-center rounded-2xl bg-[#fde9e3] text-sm font-semibold text-[#a94737] dark:bg-[#e58775]/10 dark:text-[#f1ad9e]">{{ $setupPercent }}%</span></div><div class="mt-5 h-1.5 overflow-hidden rounded-full bg-stone-100 dark:bg-white/5"><div class="h-full rounded-full bg-[#e58775] transition-all" style="width: {{ $setupPercent }}%"></div></div><div class="mt-5 space-y-3">@foreach($this->setup as $step)<div class="flex items-center gap-3 text-sm"><span @class(['grid size-6 place-items-center rounded-full', 'bg-emerald-100 text-emerald-600 dark:bg-emerald-400/10 dark:text-emerald-400' => $step['done'], 'bg-stone-100 text-stone-400 dark:bg-white/5' => ! $step['done']])>@if($step['done'])<flux:icon.check class="size-3.5" />@else<span class="size-1.5 rounded-full bg-current"></span>@endif</span><span @class(['text-stone-400 line-through' => $step['done'], 'text-stone-600 dark:text-stone-300' => ! $step['done']])>{{ $step['label'] }}</span></div>@endforeach</div></section>
            @endif
        </div>

        <div class="grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(18rem,.6fr)]">
            <section class="overflow-hidden rounded-3xl border border-stone-200 bg-white dark:border-white/10 dark:bg-zinc-900"><header class="flex items-center justify-between border-b border-stone-200 px-5 py-4 dark:border-white/10"><div><h3 class="font-semibold">Projetos recentes</h3><p class="mt-0.5 text-xs text-stone-500">Continue trabalhando nos últimos eventos.</p></div><flux:button variant="ghost" size="sm" :href="route('client.events.index')" wire:navigate>Ver todos</flux:button></header>@forelse($this->recentEvents as $event)@php($cover = $event->site->coverImageUrl())<a href="{{ route('client.builder.edit', ['event' => $event, 'page' => $event->site->pages->first()]) }}" wire:navigate class="group flex items-center gap-4 border-b border-stone-100 p-4 last:border-0 hover:bg-[#fff9f7] dark:border-white/5 dark:hover:bg-white/[.025]">@if($cover)<img src="{{ $cover }}" alt="" class="size-12 rounded-xl object-cover">@else<span class="grid size-12 shrink-0 place-items-center rounded-xl bg-[#fde9e3] text-[#b85240] dark:bg-[#e58775]/10 dark:text-[#f1ad9e]"><flux:icon.sparkles class="size-5" /></span>@endif<div class="min-w-0 flex-1"><p class="truncate text-sm font-medium">{{ $event->name }}</p><p class="mt-1 text-xs text-stone-500">Atualizado {{ $event->updated_at->diffForHumans() }}</p></div><flux:badge size="sm" :color="$event->site->status === 'published' ? 'lime' : 'zinc'">{{ $event->site->status === 'published' ? 'Publicado' : 'Rascunho' }}</flux:badge><flux:icon.chevron-right class="size-4 text-stone-300 transition group-hover:translate-x-0.5 group-hover:text-[#b85240]" /></a>@empty<div class="px-5 py-12 text-center"><flux:icon.calendar-days class="mx-auto size-7 text-stone-300" /><p class="mt-3 text-sm text-stone-500">Seus projetos aparecerão aqui.</p></div>@endforelse</section>

            <section class="rounded-3xl border border-stone-200 bg-white p-5 dark:border-white/10 dark:bg-zinc-900"><h3 class="font-semibold">Acesso rápido</h3><p class="mt-1 text-xs text-stone-500">Atalhos para o seu dia a dia.</p><div class="mt-5 grid grid-cols-2 gap-3">@foreach([['Novo evento','plus',route('client.events.index')],['Enviar mídia','cloud-arrow-up',route('client.media.index')],['Convidar equipe','user-plus',route('client.team.index')],['Configurações','cog-6-tooth',route('client.settings.index')]] as [$label,$icon,$route])<a href="{{ $route }}" wire:navigate class="group rounded-2xl border border-stone-200 p-3 transition hover:border-[#e58775] hover:bg-[#fff9f7] dark:border-white/10 dark:hover:bg-[#e58775]/5"><span class="grid size-8 place-items-center rounded-xl bg-stone-100 text-stone-500 group-hover:text-[#b85240] dark:bg-white/5 dark:text-stone-400"><flux:icon :name="$icon" class="size-4" /></span><p class="mt-3 text-xs font-medium">{{ $label }}</p></a>@endforeach</div></section>
        </div>
    </div>
</main>
